### ISSUE TITLE
不支持头条小程序吗？

### ISSUE THREAD

**Issue by songge8** [zhuige-com/jiangqie_ow_free#1]
请问还不支持头条（抖音）小程序吗？

**Comment by longwenjunjie** [comment]
使用 uniapp 开发的，头条小程序未测试，如果需求可以自行调整

**Comment by songge8** [comment]
已经测试了，头条小程序首页空白，只显示底部导航栏。uniapp文档还没看完，能力不允许自行调整啊。。。
